name = "transcribe"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
minify = true

# remove the [site] block entirely

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[build]
command = "npm run build:open-next"
upload = { format = "modules" }
